# Set the build language to Python
language: python

# Set the python version to 2.7
python: 3.7

# Install the packages
install:
  - pip install -r requirements.txt

# Run the unit test
script:
  - python run.py